version: '3.8'
services:
  mysql:
    image: mysql
    restart: unless-stopped
    env_file: 
      - .env
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  server:
    depends_on:
      - mysql
    ports:
      - 80:80
    build: .
    restart: unless-stopped
    env_file: .env
    stdin_open: true
    tty: true
