CREATE DATABASE IF NOT EXISTS board_db;
USE board_db;
CREATE TABLE IF NOT EXISTS board (
  BOARD_NO INT NOT NULL AUTO_INCREMENT,
  TITLE TEXT NOT NULL,
  CONTENT LONGTEXT NOT NULL,
  POST_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL,
  AUTHOR TEXT NOT NULL,
  PRIMARY KEY (BOARD_NO)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE comment (
  comment_num int NOT NULL AUTO_INCREMENT,
  article_num int DEFAULT NULL,
  author text,
  time date DEFAULT NULL,
  class int DEFAULT NULL,
  comment_order int DEFAULT NULL,
  group_num int DEFAULT NULL,
  content text NOT NULL,
  PRIMARY KEY (comment_num),
  KEY article_num (article_num),
  CONSTRAINT comment_ibfk_1 FOREIGN KEY (article_num) REFERENCES BOARD (BOARD_NO) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=180 DEFAULT CHARSET=utf8mb3;

